### ISSUE TITLE
Batch/transaction support for Subcollections

### ISSUE THREAD

**Issue by smddzcy** [wovalle/fireorm#139]
Hey! First of all, thanks for the great library.

I'm using `fireorm` in one of my projects now and I have an issue with batch writes and transactions in subcollections. I couldn't find any examples in your tests and I couldn't find any docs about it. Is batch writes and transactions in subcollections currently supported?

Here's my use case: I have a base object with a subcollection, and that subcollection has its own nested subcollection, so roughly `A -> B -> C`. I would like to create an `A` object, insert around 10k `B` objects in it, and insert around 500-1k `C` objects in each of those `B` objects. Obviously, doing the inserts one by one takes a long time and I would like to use the batch insert mechanism.

**Comment by wovalle** [comment]
I haven't tested transactions within subcollections of subcollections 🤔. Theoretically it should work but is untested as of now.

Are you seeing any errors? Do you get the typing information for the inner subcollection? I know @joemckie had a workaround to make this work, not really sure what it was.

**Comment by smddzcy** [comment]
I don't have any errors because I'm stuck at the very first step. I just don't know how to get the batch repository for a subcollection 🙂

```
const batch = createBatch();
batch.getRepository(DUNNO_WHAT_TO_PUT);
```

**Comment by joemckie** [comment]
I haven't implemented batches or transactions yet, but it looks like this functionality might not be completed yet.

https://github.com/wovalle/fireorm/blob/master/src/Batch/FirestoreBatch.ts#L24 getRepository should accept a `collectionPath` argument which is used to instantiate the `BaseFirestoreBatchRepository`.

**Comment by smddzcy** [comment]
@joemckie sooo... should I wait for the bugfix? if I understand correctly, we just need to add an optional parameter to that function and provide it to the `BaseFirestoreBatchRepository` constructor, i.e.

```javascript
getRepository<T extends IEntity>(entity: Instantiable<T>, collectionPath?: string) {
  return new BaseFirestoreBatchRepository(this.batch, entity, collectionPath);
}
```

**Comment by wovalle** [comment]
I guess that would be fine 😅

**Comment by skalashnyk** [comment]
Hi,

I've just started using subcollections and a little bit confused about using `batch write` in subcollections.
First of all, I read this article - https://medium.com/@wovalle/introducing-fireorm-ba7734644684
Example of using collection described there:
```
class Album {
  id: string;
  name: string;
  year: number;
}

@Collection()
export class Band {
  id: string;
  name: string;
  formationYear: number;
  genres: Array<string>;
  @SubCollection(Album)
  albums?: ISubCollection<Album>;
}
```

Please, note, that current `ISubCollection` interface (that is alias of `IRepository<T>`) does not expose `createBatch()` method - https://github.com/wovalle/fireorm/blob/f66fe7e8c85a093d335f72a67044a73b6fa385ab/src/types.ts#L80
So, how to use batch write to subcollection?

I tried the next scenario:
```
import { ISubCollection, SubCollection, Collection, getRepository } from 'fireorm';

class Child {
  id: string;
  name: string;
}

@Collection()
class Parent {
  id: string;
  name: string;
  @SubCollection(Child)
  children?: ISubCollection<Child>;
}

(async _ => {
  try {
    const repo = getRepository(Parent);

    const created = await repo.create({
      name: 'Father'
    });

    const batch = created.children?.createBatch();

    [
      {name: 'First'},
      {name: 'Last'},
    ].forEach(child => {
      batch.create(child);
    });

    await batch.commit();

    console.log(await created.children.find()); // empty array
  } catch (e) {
    console.error(e);
  }
})();
```
**Expected behaviour**
1 document in `"Parents"` collection and 2 documents in `"children"` subcollection (of this "perent" doc) were created.
**Actual behaviour**
1 document in `"Parents"` collection and 2 documents in `"children"` collection (as root collection) were created.

I'm observing this in (at least) `0.17.0` and `0.14.0` (that is referenced in this thread as on that resolves the issue).
`0.12.1` (that I have installed) works as expected
