### ISSUE TITLE
An orderBy function cannot be called more than once in the same query expression

### ISSUE THREAD

**Issue by jaynarw** [wovalle/fireorm#266]
Error: 
> An orderBy function cannot be called more than once in the same query expression

Code:
```
Comments
  .orderByDescending("pinned")
  .orderByDescending("timestamp")
  .limit(n)
  .find()
```

Firestore allows ordering using multiple fields in the same query.
Firebase Docs: 
> You can also order by multiple fields. For example, if you wanted to order by state, and within each state order by population in descending order:

**Workaround**: use customQuery to orderBy other fields.

**Comment by wovalle** [comment]
Interesting. In https://github.com/wovalle/fireorm/blob/master/src/QueryBuilder.ts#L147 and https://github.com/wovalle/fireorm/blob/master/src/QueryBuilder.ts#L156 we should store the fields that have been ordered by with (and throw if you try to orderBy twice in the same field) instead of just checking if any fields have been ordered by.
