### ISSUE TITLE
How to mock for testing

### ISSUE THREAD

**Issue by dylanstanfield** [wovalle/fireorm#80]
First off - this has been a great experience! Thanks for building fireorm. Has anyone had experience with testing/mocking a repository? Could we add a mock repository type? Currently trying to use this in my app and am unable to run tests that import `Collection` annotated models.

**Comment by dylanstanfield** [comment]
Currently using this to workaround. Unfortunately it's a bit awkward because this needs to run before I import any file imports a model with the `Collection` annotation.
```ts
import * as fireorm from 'fireorm'
import * as MockFirebase from 'mock-cloud-firestore'

const firebase = new MockFirebase()
const firestore = firebase.firestore()
fireorm.Initialize(firestore)
```

**Comment by wovalle** [comment]
That's exactly the way I'm creating the [unit tests](https://github.com/wovalle/fireorm/blob/master/src/BaseFirestoreRepository.spec.ts#L43-L50) with. About the MockRepository I don't have any clue about how it would look like 😄   Do you have examples/projects that I can follow?

@mamodom you're a software testing enthusiast, your opinion would be much appreciated!

**Comment by dylanstanfield** [comment]
Is it possible to not throw the fireorm initialization error for model annotations are imported? Possibly throw when a resulting repository is used? I'd be happy to open a PR that adds the utility above.

```
import * as fireorm from 'fireorm'

fireorm.Initialize(fireorm.MockFirestore)
// or
fireorm.InitializeMock()
```

**Comment by wovalle** [comment]
I don't think fireorm should expose either `MockFirestore` or `InitializeMock()` because internally it would have to maintain a compatible mock api of `firebase-admin/firestore` which falls out of the scope of the library (at least for now).

I'll check how some libraries deal with testing to see what can be implemented.

Also, [here](https://github.com/wovalle/fireorm/pull/81#issuecomment-535695889) I wrote why the initialization error is important. I'm open to suggestions to implement a better flow, though.
